### PR TITLE
Sync with StatsFuns

### PR DESCRIPTION
**Pull request by devmotion**
This PR updates LogExpFunctions and adds all the changes that accumulated in StatsFuns in the last 17 months.

Tests pass locally.

### CODE REVIEW

**Comment by tpapp** [comment]
Thanks! I will fix CI today and then review and merge.

**Comment by tpapp** [comment]
Closing an opening to trigger CI.

**Comment by tpapp** [comment]
Thanks for this very clean PR, merging.

**Comment by cossio** [comment]
Thanks!

**Pull request merged**
